{
 "cells": [
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [],
   "source": [
    "person = {'name': 'Jenn', 'age': 23}\n",
    "\n",
    "# sentence = 'My name is ' + person['name'] + ' and I am ' + str(person['age']) + ' years old.'\n",
    "# print(sentence)\n",
    "\n",
    "\n",
    "# sentence = 'My name is {} and I am {} years old.'.format(person['name'], person['age'])\n",
    "# print(sentence)\n",
    "\n",
    "\n",
    "# sentence = 'My name is {0} and I am {1} years old.'.format(person['name'], person['age'])\n",
    "# print(sentence)\n",
    "\n",
    "\n",
    "# tag = 'h1'\n",
    "# text = 'This is a headline'\n",
    "\n",
    "# sentence = '<{0}>{1}</{0}>'.format(tag, text)\n",
    "# print(sentence)\n",
    "\n",
    "\n",
    "sentence = 'My name is {0} and I am {1} years old.'.format(person['name'], person['age'])\n",
    "print(sentence)\n",
    "\n",
    "\n",
    "class Person():\n",
    "\n",
    "    def __init__(self, name, age):\n",
    "        self.name = name\n",
    "        self.age = age\n",
    "\n",
    "p1 = Person('Jack', '33')\n",
    "\n",
    "sentence = 'My name is {0.name} and I am {0.age} years old.'.format(p1)\n",
    "print(sentence)\n",
    "\n",
    "# sentence = 'My name is {name} and I am {age} years old.'.format(name='Jenn', age='30')\n",
    "# print(sentence)\n",
    "\n",
    "# sentence = 'My name is {name} and I am {age} years old.'.format(**person)\n",
    "# print(sentence)\n",
    "\n",
    "# for i in range(1, 11):\n",
    "#     sentence = 'The value is {}'.format(i)\n",
    "#     print(sentence)\n",
    "\n",
    "\n",
    "# pi = 3.14159265\n",
    "\n",
    "# sentence = 'Pi is equal to {}'.format(pi)\n",
    "\n",
    "# print(sentence)\n",
    "\n",
    "\n",
    "sentence = '1 MB is equal to {} bytes'.format(1000**2)\n",
    "\n",
    "print(sentence)\n",
    "\n",
    "\n",
    "import datetime\n",
    "\n",
    "my_date = datetime.datetime(2016, 9, 24, 12, 30, 45)\n",
    "\n",
    "# print(my_date)\n",
    "\n",
    "# March 01, 2016\n",
    "\n",
    "sentence = '{:%B %d, %Y}'.format(my_date)\n",
    "\n",
    "print(sentence)\n",
    "\n",
    "# March 01, 2016 fell on a Tuesday and was the 061 day of the year.\n",
    "\n",
    "sentence = '{:%B %d, %Y} fell on a {} and was the {} day of the year'.format(my_date)\n",
    "\n",
    "print(sentence)"
   ]
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "Python 3",
   "language": "python",
   "name": "python3"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.6.7"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 2
}
